#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : numpy
Version  : 1.17.2
Release  : 156
URL      : https://files.pythonhosted.org/packages/ac/36/325b27ef698684c38b1fe2e546e2e7ef9cecd7037bcdb35c87efec4356af/numpy-1.17.2.zip
Source0  : https://files.pythonhosted.org/packages/ac/36/325b27ef698684c38b1fe2e546e2e7ef9cecd7037bcdb35c87efec4356af/numpy-1.17.2.zip
Summary  : NumPy is the fundamental package for array computing with Python.
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause MIT Python-2.0
Requires: numpy-bin = %{version}-%{release}
Requires: numpy-license = %{version}-%{release}
Requires: numpy-python = %{version}-%{release}
Requires: numpy-python3 = %{version}-%{release}
Requires: Cython
Requires: gcc-libs-math
Requires: nose
Requires: openblas
BuildRequires : Cython
BuildRequires : Jinja2
BuildRequires : Sphinx
BuildRequires : buildreq-distutils3
BuildRequires : gfortran
BuildRequires : nose
BuildRequires : openblas
BuildRequires : python-core
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools-legacypython
Patch1: build.patch
Patch2: avx2-distutils.patch
Patch3: avx2-fortran-distutils.patch
Patch4: timestamp.patch
Patch5: cve-2017-12852.nopatch
Patch6: 0001-AVX-implementation-with-intrinsic-for-small_correlat_v1.patch

%description
- a powerful N-dimensional array object
        - sophisticated (broadcasting) functions
        - tools for integrating C/C++ and Fortran code
        - useful linear algebra, Fourier transform, and random number capabilities
        - and much more
        
        Besides its obvious scientific uses, NumPy can also be used as an efficient
        multi-dimensional container of generic data. Arbitrary data-types can be
        defined. This allows NumPy to seamlessly and speedily integrate with a wide
        variety of databases.
        
        All NumPy wheels distributed on PyPI are BSD licensed.

%package bin
Summary: bin components for the numpy package.
Group: Binaries
Requires: numpy-license = %{version}-%{release}

%description bin
bin components for the numpy package.


%package dev
Summary: dev components for the numpy package.
Group: Development
Requires: numpy-bin = %{version}-%{release}
Provides: numpy-devel = %{version}-%{release}
Requires: numpy = %{version}-%{release}

%description dev
dev components for the numpy package.


%package license
Summary: license components for the numpy package.
Group: Default

%description license
license components for the numpy package.


%package python
Summary: python components for the numpy package.
Group: Default
Requires: numpy-python3 = %{version}-%{release}

%description python
python components for the numpy package.


%package python3
Summary: python3 components for the numpy package.
Group: Default
Requires: python3-core

%description python3
python3 components for the numpy package.


%prep
%setup -q -n numpy-1.17.2
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch6 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1568960467
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -mzero-caller-saved-regs=used "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build  --fcompiler=gnu95

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/numpy
cp doc/scipy-sphinx-theme/LICENSE.txt %{buildroot}/usr/share/package-licenses/numpy/doc_scipy-sphinx-theme_LICENSE.txt
cp doc/source/license.rst %{buildroot}/usr/share/package-licenses/numpy/doc_source_license.rst
cp doc/sphinxext/LICENSE.txt %{buildroot}/usr/share/package-licenses/numpy/doc_sphinxext_LICENSE.txt
cp numpy/linalg/lapack_lite/LICENSE.txt %{buildroot}/usr/share/package-licenses/numpy/numpy_linalg_lapack_lite_LICENSE.txt
cp numpy/ma/LICENSE %{buildroot}/usr/share/package-licenses/numpy/numpy_ma_LICENSE
cp numpy/random/src/mt19937/LICENSE.md %{buildroot}/usr/share/package-licenses/numpy/numpy_random_src_mt19937_LICENSE.md
cp numpy/random/src/pcg64/LICENSE.md %{buildroot}/usr/share/package-licenses/numpy/numpy_random_src_pcg64_LICENSE.md
cp numpy/random/src/philox/LICENSE.md %{buildroot}/usr/share/package-licenses/numpy/numpy_random_src_philox_LICENSE.md
cp numpy/random/src/sfc64/LICENSE.md %{buildroot}/usr/share/package-licenses/numpy/numpy_random_src_sfc64_LICENSE.md
cp tools/npy_tempita/license.txt %{buildroot}/usr/share/package-licenses/numpy/tools_npy_tempita_license.txt
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/f2py
/usr/bin/f2py3
/usr/bin/f2py3.7

%files dev
%defattr(-,root,root,-)
/usr/lib/python3.7/site-packages/numpy/core/include/numpy/__multiarray_api.h
/usr/lib/python3.7/site-packages/numpy/core/include/numpy/__ufunc_api.h
/usr/lib/python3.7/site-packages/numpy/core/include/numpy/_neighborhood_iterator_imp.h
/usr/lib/python3.7/site-packages/numpy/core/include/numpy/_numpyconfig.h
/usr/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h
/usr/lib/python3.7/site-packages/numpy/core/include/numpy/arrayscalars.h
/usr/lib/python3.7/site-packages/numpy/core/include/numpy/halffloat.h
/usr/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h
/usr/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h
/usr/lib/python3.7/site-packages/numpy/core/include/numpy/noprefix.h
/usr/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h
/usr/lib/python3.7/site-packages/numpy/core/include/numpy/npy_3kcompat.h
/usr/lib/python3.7/site-packages/numpy/core/include/numpy/npy_common.h
/usr/lib/python3.7/site-packages/numpy/core/include/numpy/npy_cpu.h
/usr/lib/python3.7/site-packages/numpy/core/include/numpy/npy_endian.h
/usr/lib/python3.7/site-packages/numpy/core/include/numpy/npy_interrupt.h
/usr/lib/python3.7/site-packages/numpy/core/include/numpy/npy_math.h
/usr/lib/python3.7/site-packages/numpy/core/include/numpy/npy_no_deprecated_api.h
/usr/lib/python3.7/site-packages/numpy/core/include/numpy/npy_os.h
/usr/lib/python3.7/site-packages/numpy/core/include/numpy/numpyconfig.h
/usr/lib/python3.7/site-packages/numpy/core/include/numpy/old_defines.h
/usr/lib/python3.7/site-packages/numpy/core/include/numpy/oldnumeric.h
/usr/lib/python3.7/site-packages/numpy/core/include/numpy/random/bitgen.h
/usr/lib/python3.7/site-packages/numpy/core/include/numpy/ufuncobject.h
/usr/lib/python3.7/site-packages/numpy/core/include/numpy/utils.h

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/numpy/doc_scipy-sphinx-theme_LICENSE.txt
/usr/share/package-licenses/numpy/doc_source_license.rst
/usr/share/package-licenses/numpy/doc_sphinxext_LICENSE.txt
/usr/share/package-licenses/numpy/numpy_linalg_lapack_lite_LICENSE.txt
/usr/share/package-licenses/numpy/numpy_ma_LICENSE
/usr/share/package-licenses/numpy/numpy_random_src_mt19937_LICENSE.md
/usr/share/package-licenses/numpy/numpy_random_src_pcg64_LICENSE.md
/usr/share/package-licenses/numpy/numpy_random_src_philox_LICENSE.md
/usr/share/package-licenses/numpy/numpy_random_src_sfc64_LICENSE.md
/usr/share/package-licenses/numpy/tools_npy_tempita_license.txt

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
